server:
  port: 8082

spring:
  datasource:
    name: course_prepare_datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.14.150:3306/course_prepare?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&userSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ooOO_000000
  application:
    name: course-price

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:-}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:}){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

course-list:
  ribbon:
    NFLoadBanlancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

feign:
  hystrix:
    enabled: true